const axios = require("axios");
const https = require("https");
// 2. Tạo Agent để bỏ qua lỗi SSL
const agent = new https.Agent({
  rejectUnauthorized: false,
});
const hs = [
  {
    enforcement: {
      attrs: {
        sobanan: "436/QĐST-HNGĐ",
        qd1loai: "Hôn nhân và gia đình",
        ngaybanan: "2025-08-13T17:00:00Z",
        toaan: "Thi hành án dân sự thành phố Hồ Chí Minh",
      },
      decisionId: "000061pyILrkyfEOVJv8WA",
      decisionNumber: "21101/QĐ-THADS",
      requestDate: "2025-11-25T09:48:41Z",
      type: "is_proactive",
      contentRequirements: {
        base64: null,
        html: "Án phí hôn nhân và gia đình sơ thẩm là 150.000 đồng (Một trăm năm mươi nghìn đồng) do bà Nhung tự nguyện chịu, được cấn trừ vào số tiền tạm ứng án phí 300.000 đồng (Ba trăm nghìn đồng) do bà Nhung đã nộp theo biên lai thu tiền số 0016254 ngày 09/10/2024 của Chi cục Thi hành án dân sự huyện Củ Chi, Thành phố Hồ Chí Minh (nay là Phòng Thi hành án dân sự Khu vực 8-Thành phố Hồ Chí Minh), hoàn số tiền còn lại 150.000 đồng (Một trăm năm mươi nghìn đồng) cho bà Nhung.",
      },
      propertyInfo: {
        base64: null,
        html: null,
      },
      requester: null,
      requesterId: null,
      requesterAddress: null,
      enforcementAgency: "Thi hành án dân sự thành phố Hồ Chí Minh",
      status: "dangthihanh",
      period: "thongbaoquyetdinhtha",
      action: "RA_QUYET_DINH",
      assigneeName: "diempth.hcm@moj.gov.vn",
      assignee: "test_candv.hcm@moj.gov.vn",
      preAssignee: null,
      ticketId: "00006lKIW9lwI0852Mo96",
      envelopeId: null,
      judgmentInfo: {
        base64: null,
        html: "Căn cứ Quyết định công nhận thuận tình ly hôn và sự thỏa thuận của các đương sự số 436/2025/QĐST-HNGĐ ngày 14 tháng 8 năm 2025 của Tòa án nhân dân Khu vực 8 - Thành phố Hồ Chí Minh.",
      },
      obligorName: {
        base64: null,
        html: "bà Nguyễn Thị Cẩm Nhung, địa chỉ: Ấp 8, xã Phú Hòa Đông, Thành phố Hồ Chí Minh.",
      },
      lookup: null,
      receivedDate: "2025-11-25T09:48:30Z",
      signedDate: "2025-11-26T02:41:04Z",
      rawData: {
        requester_goc: "",
        judgmentInfo:
          "Căn cứ Quyết định công nhận thuận tình ly hôn và sự thỏa thuận của các đương sự số 436/2025/QĐST-HNGĐ ngày 14 tháng 8 năm 2025 của Tòa án nhân dân Khu vực 8 - Thành phố Hồ Chí Minh.",
        anphihsst: "",
        kpthatheokhoan:
          "1. Công nhận sự thuận tình ly hôn giữa bà Nguyễn Thị Cẩm Nhung và ông Nguyễn Văn Thanh. 2. Công nhận sự thỏa thuận của các đương sự, cụ thể như sau: - Án phí hôn nhân và gia đình sơ thẩm là 150.000 (một trăm năm mươi nghìn) đồng do bà Nhung tự nguyện chịu, được cấn trừ vào số tiền tạm ứng án phí 300.000 (ba trăm nghìn) đồng do bà Nhung đã nộp theo Biên lai thu tiền số 0016254 ngày 09/10/2024 của Chi cục thi hành án dân sự huyện Củ Chi, Thành phố Hồ Chí Minh (Nay là Phòng Thi hành án dân sự khu vực 8-Thành phố Hồ Chí Minh), hoàn số tiền còn lại 150.000 (một trăm năm mươi nghìn) đồng cho bà Nhung.",
        type: "",
        filetlkhac: null,
        anphihanhchinhst: "",
        dchingphaiTHA_convert: null,
        filegdt_convert: null,
        diachithuongtrunguoiyc_convert: "",
        xacnhan:
          "bà Nhung đã nộp theo Biên lai thu tiền số 0016254 ngày 09/10/2024 của Chi cục thi hành án dân sự huyện Củ Chi, Thành phố Hồ Chí Minh (Nay là Phòng Thi hành án dân sự khu vực 8-Thành phố Hồ Chí Minh)",
        cqbh: "THI HÀNH ÁN DÂN SỰ THÀNH PHỐ HỒ CHÍ MINH",
        ghinhan: "",
        truythu: "",
        requester: "",
        qr: "https://prod-2025-thads-qdtha-attachment-hn2.s3-han02.fptcloud.com/11/5682/qr/000061pyILrkyfEOVJv8WA/1764119535880/000061pyILrkyfEOVJv8WA.png",
        requesterId: "",
        "10d": "Không",
        notificationPost: "",
        anphidspt: "",
        dchingphaiTHA: "",
        hotencbtiepnhanqduttt: "",
        filegdt: null,
        sdtcbtiepnhanqduttt: "",
        khuvucxlan: "",
        diachithuongtrunguoiyc: "",
        ttds: "bà Nguyễn Thị Cẩm Nhung, địa chỉ: Ấp 8, xã Phú Hòa Đông, Thành phố Hồ Chí Minh.",
        ngaybh: "2025-11-26T02:39:44Z",
        hotenchv: "",
        fileqddbh: [
          {
            data: '{\n  "bucketName" : "econ-eform-demo-hn2",\n  "keyName" : "anonymous/20251126/1764124802659_File ký QDTHA chủ dộng_QT4_TH(Chánh VP_2).pdf",\n  "beanName" : "s3ClientSecond"\n}',
            name: "File ký QDTHA chủ dộng_QT4_TH(Chánh VP_2).pdf",
            size: "1.664088249206543",
            downloadding: false,
          },
        ],
        giaoxuly: "",
        nhanlai: "",
        ticketId: "00006lKIW9lwI0852Mo96",
        status: "cph_qdthacd",
        emailtruongkvchanhvp: "vupn.hcm@moj.gov.vn",
        filept_convert: null,
        khoan_convert:
          "Án phí hôn nhân và gia đình sơ thẩm là 150.000 đồng (Một trăm năm mươi nghìn đồng) do bà Nhung tự nguyện chịu, được cấn trừ vào số tiền tạm ứng án phí 300.000 đồng (Ba trăm nghìn đồng) do bà Nhung đã nộp theo biên lai thu tiền số 0016254 ngày 09/10/2024 của Chi cục Thi hành án dân sự huyện Củ Chi, Thành phố Hồ Chí Minh (nay là Phòng Thi hành án dân sự Khu vực 8-Thành phố Hồ Chí Minh), hoàn số tiền còn lại 150.000 đồng (Một trăm năm mươi nghìn đồng) cho bà Nhung.",
        mophongtoatk: "",
        fileguq: "",
        legalRepresentative: null,
        anphilaodongst: "",
        assigneeName: "diempth.hcm@moj.gov.vn",
        huylenhkebien: "",
        ttds_convert:
          "bà Nguyễn Thị Cẩm Nhung, địa chỉ: Ấp 8, xã Phú Hòa Đông, Thành phố Hồ Chí Minh.",
        hotenngphaiTHA_convert: "Bà Nguyễn Thị Cẩm Nhung",
        duykebien: "",
        hoten: "Bà Nguyễn Thị Cẩm Nhung",
        chucdanhldtha: "Phó Trưởng Thi hành án dân sự",
        truythuthue: "",
        kpthatheondba:
          "Án phí hôn nhân và gia đình sơ thẩm là 150.000 đồng (Một trăm năm mươi nghìn đồng) do bà Nhung tự nguyện chịu, được cấn trừ vào số tiền tạm ứng án phí 300.000 đồng (Ba trăm nghìn đồng) do bà Nhung đã nộp theo biên lai thu tiền số 0016254 ngày 09/10/2024 của Chi cục Thi hành án dân sự huyện Củ Chi, Thành phố Hồ Chí Minh (nay là Phòng Thi hành án dân sự Khu vực 8-Thành phố Hồ Chí Minh), hoàn số tiền còn lại 150.000 đồng (Một trăm năm mươi nghìn đồng) cho bà Nhung.",
        khat: "",
        agency: "79",
        anphichiataisan: "",
        anphilyhon:
          "Án phí hôn nhân và gia đình sơ thẩm là 150.000 (một trăm năm mươi nghìn) đồng do bà Nhung tự nguyện chịu",
        sobaqd: "436/QĐST-HNGĐ",
        fileguq_convert: "",
        filedyc_convert: "",
        phongtoataisan: "",
        sdtvanthu: "0999999999",
        hotencbthuly: "diempth.hcm@moj.gov.vn",
        tichthusungcongvatchung: "",
        decisionNumber: " 21101/QĐ-THADS",
        hinhthucthongbao: "Thông báo qua SMS",
        tralai: "",
        lephi: "",
        noiutdi: "",
        sdtchv: "",
        signedDate: 1764124864.829154,
        filedyc: "",
        emailcbthuly: "diempth.hcm@moj.gov.vn",
        judgmentType: "is_proactive",
        khautru: "",
        fileqd: [
          {
            data: '{\n  "bucketName" : "econ-eform-demo-hn2",\n  "keyName" : "anonymous/20251124/1764003526463_QĐ 436 ngày 14.8.2025.pdf",\n  "beanName" : "s3ClientSecond"\n}',
            name: "QĐ 436 ngày 14.8.2025.pdf",
            size: "0.7",
            downloadding: false,
          },
        ],
        filept: null,
        diachikhacnguoiyc: "",
        emailcbtiepnhanqduttt: "",
        anphidsst: "",
        giaosohuu: "",
        ttbaqd:
          "Số 436/2025/QĐST-HNGĐ; ngày 14 tháng 8 năm 2025; của TÒA ÁN NHÂN DÂN KHU VỰC 8",
        emailldtha: "hongtp.hcm@moj.gov.vn",
        diachikhacnguoiyc_convert: "",
        giaosotien: "",
        huyqdthugiu: "",
        toabh: "Tòa án nhân dân khu vực 8 - Hồ Chí Minh",
        vientro: "",
        phattien: "",
        ndcc: "Căn cứ Quyết định công nhận thuận tình ly hôn và sự thỏa thuận của các đương sự số 436/2025/QĐST-HNGĐ ngày 14 tháng 8 năm 2025 của Tòa án nhân dân Khu vực 8 - Thành phố Hồ Chí Minh.",
        lenhkebien: "",
        sdttruongkvchanhvp: "0918384614",
        filett_convert: null,
        anphihspt: "",
        thuhoidat: "",
        anphihanhchinhpt: "",
        notificationEmail: "",
        areaCode: "08",
        hotenngphaiTHA: "Bà Nguyễn Thị Cẩm Nhung",
        notificationkhac: "",
        sdtcbthuly: "0999999999",
        fileqd_convert: [
          {
            data: '{"bucketName":"econ-eform-demo-hn2","keyName":"anonymous/20251124/1764003526463_QĐ 436 ngày 14.8.2025_convert_docx.pdf","beanName":"s3ClientSecond"}',
            name: "1764003526463_QĐ 436 ngày 14.8.2025_convert_docx.pdf",
            size: "0.7",
            downloadding: false,
          },
        ],
        name: "QD-THADS.436/QĐST-HNGĐ.Bà Nguyễn Thị Cẩm Nhung",
        requester_1: "",
        sdtldtha: "0971591611",
        filest_convert: null,
        xuphat: "",
        tamgiudambao: "",
        link: "https://kyta.fpt.com/thads-tracuuqd/?lookup=p4EiKPrHai9z9G",
        hotenldtha: "Trần Phương Hồng",
        emailvanthu: "vanthu.hcm@moj.gov.vn",
        emailchv: "quynhltn.hcm@moj.gov.vn",
        phongtoataikhoan: "",
        tieptuckebien: "",
        loaian: "Hôn nhân và gia đình",
        filetlkhac_convert: null,
        hoantra: "",
        filest: null,
        hotentruongkvchanhvp: "Phạm Ngọc Vũ",
        tinh: "Thành phố Hồ Chí Minh",
        hotenvanthu: "Văn thư đơn vị TP Hồ Chí Minh",
        ndcc_convert:
          "Căn cứ Quyết định công nhận thuận tình ly hôn và sự thỏa thuận của các đương sự số 436/2025/QĐST-HNGĐ ngày 14 tháng 8 năm 2025 của Tòa án nhân dân Khu vực 8 - Thành phố Hồ Chí Minh.",
        hoanlai:
          "hoàn số tiền còn lại 150.000 (một trăm năm mươi nghìn) đồng cho bà Nhung.",
        tieptuctamgiu: "",
        tichthusungcongsotien: "",
        anphicapduong: "",
        filecv_convert: "",
        filecv: "",
        dstoi: [
          ["Chương", "Mục", "Điều"],
          ["", "", ""],
          ["", "", ""],
        ],
        notificationSms: "",
        notificationsdd: "",
        qd1ghichu: "Ra quyết định",
        anphilaodongpt: "",
        filett: null,
        huyquyetdinh: "",
        boithuongnn: "",
        thuhoisotien: "",
        tichthutienhuy: "",
      },
      totalMoney: 300000,
      totalReceived: 0,
      remainingAmount: 300000,
    },
    enforcementDocumentRequests: [
      {
        enforcementDocument: {
          resourceType: "attatch",
          number: "21101/QĐ-THADS",
          name: "QĐ THADS 436/QĐST-HNGĐ Bà Nguyễn Thị Cẩm Nhung",
          releaseDate: "2025-11-26T02:41:04Z",
          submissionDate: "2025-11-25T09:48:30Z",
          page: null,
          businessType: "attach",
          documentType: "qdtha",
          status: "approved",
          resourceSystem: "eQD",
          butLuc: "1",
          deletionFlag: false,
        },
        objectStorages: [
          {
            resourceId: "judgment_decision_000061pyILrkyfEOVJv8WA",
            fileName: "QĐ THADS 436/QĐST-HNGĐ Bà Nguyễn Thị Cẩm Nhung",
            typeLocation: null,
            code: null,
            beanName: "s3ClientSecond",
            bucketName: "prod-2025-envelope-second",
            keyName:
              "11/completed//storage-01/5682/0000615O6Ik8dIJpJ6560afNaN8.pdf",
            documentType: "envelope",
            resourceType: "DOCUMENT_TYPE_QDTHA",
            contentType: "application/pdf",
            documentSize: 1744928,
            resourceSystem: "envelope",
            description: null,
            envelopeId: "000069Q3FQk0HnGnNPX0xCVyVk",
          },
        ],
      },
      {
        enforcementDocument: {
          resourceType: "attatch",
          number: "21101/QĐ-THADS",
          name: "QĐ 436 ngày 14.8.2025.pdf",
          releaseDate: "2025-11-26T02:41:04Z",
          submissionDate: "2025-11-25T09:48:30Z",
          page: null,
          businessType: "attach",
          documentType: "qdtha",
          status: "approved",
          resourceSystem: "eQD",
          butLuc: "2",
          deletionFlag: false,
        },
        objectStorages: [
          {
            resourceId: "judgment_decision_000061pyILrkyfEOVJv8WA",
            fileName: "QĐ 436 ngày 14.8.2025.pdf",
            typeLocation: null,
            code: null,
            beanName: "s3ClientSecond",
            bucketName: "econ-eform-demo-hn2",
            keyName:
              "anonymous/20251124/1764003526463_QĐ 436 ngày 14.8.2025.pdf",
            documentType: "erequest",
            resourceType: "attatch",
            contentType: null,
            documentSize: 734003,
            resourceSystem: "eRequest",
            description: null,
            envelopeId: null,
          },
        ],
      },
      {
        enforcementDocument: {
          resourceType: "attatch",
          number: "21101/QĐ-THADS",
          name: "1764003526463_QĐ 436 ngày 14.8.2025_convert_docx.pdf",
          releaseDate: "2025-11-26T02:41:04Z",
          submissionDate: "2025-11-25T09:48:30Z",
          page: null,
          businessType: "attach",
          documentType: "qdtha",
          status: "approved",
          resourceSystem: "eQD",
          butLuc: "3",
          deletionFlag: false,
        },
        objectStorages: [
          {
            resourceId: "judgment_decision_000061pyILrkyfEOVJv8WA",
            fileName: "1764003526463_QĐ 436 ngày 14.8.2025_convert_docx.pdf",
            typeLocation: null,
            code: null,
            beanName: "s3ClientSecond",
            bucketName: "econ-eform-demo-hn2",
            keyName:
              "anonymous/20251124/1764003526463_QĐ 436 ngày 14.8.2025_convert_docx.pdf",
            documentType: "erequest",
            resourceType: "attatch",
            contentType: null,
            documentSize: 734003,
            resourceSystem: "eRequest",
            description: null,
            envelopeId: null,
          },
        ],
      },
      {
        enforcementDocument: {
          resourceType: "attatch",
          number: "21101/QĐ-THADS",
          name: "File ký QDTHA chủ dộng_QT4_TH(Chánh VP_2).pdf",
          releaseDate: "2025-11-26T02:41:04Z",
          submissionDate: "2025-11-25T09:48:30Z",
          page: null,
          businessType: "attach",
          documentType: "qdtha",
          status: "approved",
          resourceSystem: "eQD",
          butLuc: "4",
          deletionFlag: false,
        },
        objectStorages: [
          {
            resourceId: "judgment_decision_000061pyILrkyfEOVJv8WA",
            fileName: "File ký QDTHA chủ dộng_QT4_TH(Chánh VP_2).pdf",
            typeLocation: null,
            code: null,
            beanName: "s3ClientSecond",
            bucketName: "econ-eform-demo-hn2",
            keyName:
              "anonymous/20251126/1764124802659_File ký QDTHA chủ dộng_QT4_TH(Chánh VP_2).pdf",
            documentType: "erequest",
            resourceType: "attatch",
            contentType: null,
            documentSize: 1744923,
            resourceSystem: "eRequest",
            description: null,
            envelopeId: null,
          },
        ],
      },
    ],
    enforcementParties: [
      {
        name: "Nguyễn Thị Cẩm Nhung",
        type: "P",
        attrs: {
          dob: null,
          ma_xa: null,
          ma_tinh: null,
          quoc_tich: null,
          represent: null,
          chuc_danh_dai_dien: null,
        },
        email: null,
        gender: null,
        birthDay: null,
        subjects: "ncqlnv",
        description: null,
        phoneNumber: null,
        deletionFlag: false,
        identification: null,
        permanentAddress: "Ấp 8, xã Phú Hòa Đông, Thành phố Hồ Chí Minh.",
        temporaryAddress: "Ấp 8, xã Phú Hòa Đông, Thành phố Hồ Chí Minh.",
      },
      {
        name: "Chi cục Thi hành án dân sự huyện Củ Chi, Thành phố Hồ Chí Minh",
        type: "O",
        attrs: {
          dob: null,
          ma_xa: null,
          ma_tinh: null,
          quoc_tich: null,
          represent: null,
          chuc_danh_dai_dien: null,
        },
        email: null,
        gender: null,
        birthDay: null,
        subjects: "ncqlnv",
        description: null,
        phoneNumber: null,
        deletionFlag: false,
        identification: null,
        permanentAddress: null,
        temporaryAddress: null,
      },
    ],
    businessOperationDetails: [
      {
        note: null,
        paid: 0,
        rest: 150000,
        type: "an_phi",
        attrs: {
          currency: "VND",
        },
        issue: null,
        money: 150000,
        exempt: null,
        period: "thongbaoquyetdinhtha",
        reason: null,
        reduce: null,
        status: "dangthihanh",
        addition: null,
        assetType: null,
        description: "Án phí hôn nhân và gia đình sơ thẩm",
        obligorName: {
          html: "Nguyễn Thị Cẩm Nhung",
          base64: null,
        },
        postponedTo: null,
        businessType: "financial",
        personalInfos: null,
        postponedFrom: null,
        processingType: null,
        donvinhanutxlts: null,
        idhosonhanUTXLTS: null,
        relatedBusinessId: null,
        emailchvnhanUTXLTS: null,
        obligorName: {
          html: "Chi cục Thi hành án dân sự huyện Củ Chi, Thành phố Hồ Chí Minh",
          base64: null,
        },
      },
      {
        note: null,
        paid: 0,
        rest: 150000,
        type: "tra_tien",
        attrs: {
          currency: "VND",
        },
        issue: null,
        money: 150000,
        exempt: null,
        period: "thongbaoquyetdinhtha",
        reason: null,
        reduce: null,
        status: "dangthihanh",
        addition: null,
        assetType: null,
        description: "Hoàn trả tiền tạm ứng án phí",
        obligorName: {
          html: "Chi cục Thi hành án dân sự huyện Củ Chi, Thành phố Hồ Chí Minh",
          base64: null,
        },
        postponedTo: null,
        businessType: "financial",
        personalInfos: null,
        postponedFrom: null,
        processingType: null,
        donvinhanutxlts: null,
        idhosonhanUTXLTS: null,
        relatedBusinessId: null,
        emailchvnhanUTXLTS: null,
        obligorName: {
          html: "Nguyễn Thị Cẩm Nhung",
          base64: null,
        },
      },
    ],
  },
  {
    enforcement: {
      attrs: {
        sobanan: "109/2025/QĐST-HNGĐ",
        qd1loai: "Hôn nhân và gia đình",
        ngaybanan: "2025-09-21T17:00:00Z",
        toaan: "Thi hành án dân sự tỉnh Đồng Nai",
      },
      decisionId: "000061BXIg2ngtgMaB5mKx",
      decisionNumber: "7462/QĐ-THADS",
      requestDate: "2025-12-11T11:02:04Z",
      type: "is_proactive",
      contentRequirements: {
        base64: null,
        html: "Hoàn trả cho ông Tạ Hùng số tiền 300.000 đồng (Ba trăm ngàn đồng) tạm ứng án phí đã nộp theo biên lai thu số 0007410 ngày 12/6/2025 của Chi cục Thi hành án dân sự thành phố Biên Hòa, tỉnh Đồng Nai (nay là Phòng thi hành án dân sự Khu vực 1 - Đồng Nai).",
      },
      propertyInfo: {
        base64: null,
        html: null,
      },
      requester: null,
      requesterId: null,
      requesterAddress: null,
      enforcementAgency: "Thi hành án dân sự tỉnh Đồng Nai",
      status: "dangthihanh",
      period: "thongbaoquyetdinhtha",
      action: "RA_QUYET_DINH",
      assigneeName: "duongpb.dni@moj.gov.vn",
      assignee: "test_candv.hcm@moj.gov.vn",
      preAssignee: null,
      ticketId: "00006pyIok6BfEOwmBxAd",
      envelopeId: null,
      judgmentInfo: {
        base64: null,
        html: "Căn cứ Quyết định số 143/2025/QĐST-HNGĐ ngày 22 tháng 9 năm 2025 của Toà án nhân dân Khu vực 1 – Đồng Nai; Căn cứ Quyết định sửa chữa, bổ sung số 110/2025/QĐ-SCBSQĐ ngày 27 tháng 10 năm 2025 của Toà án nhân dân Khu vực 1 – Đồng Nai;",
      },
      obligorName: {
        base64: null,
        html: "Ông Tạ Hùng, sinh năm 1982; Địa chỉ: 170, tổ 25, khu phố 5, phường Long Bình, thành phố Biên Hoà, tỉnh Đồng Nai (nay là khu phố 31, phường Long Bình, tỉnh Đồng Nai).",
      },
      lookup: null,
      receivedDate: "2025-12-05T01:44:44Z",
      signedDate: "2025-12-09T07:35:46Z",
      rawData: {
        requester_goc: "",
        judgmentInfo:
          "Căn cứ Quyết định số 143/2025/QĐST-HNGĐ ngày 22 tháng 9 năm 2025 của Toà án nhân dân Khu vực 1 – Đồng Nai; Căn cứ Quyết định sửa chữa, bổ sung số 110/2025/QĐ-SCBSQĐ ngày 27 tháng 10 năm 2025 của Toà án nhân dân Khu vực 1 – Đồng Nai;",
        anphihsst: "",
        kpthatheokhoan:
          "1. Đình chỉ giải quyết vụ án dân sự thụ lý số 1373/2025/TLST-HNGĐ ngày 23/6/2025 về việc “Ly hôn” giữa: Ông Tạ Hùng, sinh năm: 1982, Địa chỉ: 170 tổ 25, khu phố 5, phường Long Bình, TP Biên Hoà, Đồng Nai (nay là khu phố 31, phường Long Bình, tỉnh Đồng Nai) và Bà Từ Lê Thu Thuỷ, sinh năm: 1983, Địa chỉ: 223/3C, tổ 14, khu phố 4, phường Hoà Bình, TP Biên Hoà, Đồng Nai (nay là khu phố Hoà Bình, phường Trấn Biên, tỉnh Đồng Nai). 2. Hậu quả của việc đình chỉ: Đương sự được quyền khởi kiện lại vụ án theo quy định tại Điều 218 Bộ luật tố tụng dân sự. Hoàn lại cho ông Tạ Hùng số tiền 300.000 đồng (Ba trăm ngàn đồng) tạm ứng án phí sơ thẩm theo biên lai thu số 0007410 ngày 12/6/2025 của Chi Cục thi hành án dân sự thành phố Biên Hòa. 3. Đương sự có quyền kháng cáo, Viện kiểm sát nhân dân Khu vực 1 – Đồng Nai có quyền kháng nghị quyết định này trong thời hạn 07 ngày kể từ ngày nhận được quyết định hoặc kể từ ngày quyết định được niêm yết theo quy định của Bộ luật tố tụng dân sự.",
        type: "",
        filetlkhac: [
          {
            data: '{\n  "bucketName" : "econ-eform-demo-hn2",\n  "keyName" : "anonymous/20251126/1764145042266_BL 7401.pdf",\n  "beanName" : "s3ClientSecond"\n}',
            name: "BL 7401.pdf",
            size: "1.45",
            downloadding: false,
          },
          {
            data: '{\n  "bucketName" : "econ-eform-demo-hn2",\n  "keyName" : "anonymous/20251126/1764145044740_TB 110.27.10.25.pdf",\n  "beanName" : "s3ClientSecond"\n}',
            name: "TB 110.27.10.25.pdf",
            size: "0.54",
            downloadding: false,
          },
        ],
        anphihanhchinhst: "",
        dchingphaiTHA_convert:
          "170, tổ 25, khu phố 5, phường Long Bình, thành phố Biên Hoà, tỉnh Đồng Nai",
        rejectCode: null,
        requesterName: null,
        diachithuongtrunguoiyc_convert: "",
        xacnhan: "",
        cqbh: "THI HÀNH ÁN DÂN SỰ TỈNH ĐỒNG NAI",
        ghinhan: "",
        truythu: "",
        requester: "",
        qr: "https://prod-2025-thads-qdtha-attachment-hn2.s3-han02.fptcloud.com/12/5682/qr/000061BXIg2ngtgMaB5mKx/1765160840639/000061BXIg2ngtgMaB5mKx.png",
        requesterId: "",
        "10d": "Không",
        notificationPost: "",
        anphidspt: "",
        dchingphaiTHA:
          "170, tổ 25, khu phố 5, phường Long Bình, thành phố Biên Hoà, tỉnh Đồng Nai",
        diachi:
          "170, tổ 25, khu phố 5, phường Long Bình, thành phố Biên Hoà, tỉnh Đồng Nai",
        hotencbtiepnhanqduttt: "",
        sdtcbtiepnhanqduttt: "",
        khuvucxlan: "",
        diachithuongtrunguoiyc: "",
        ttds: "Ông Tạ Hùng, sinh năm 1982; Địa chỉ: 170, tổ 25, khu phố 5, phường Long Bình, thành phố Biên Hoà, tỉnh Đồng Nai (nay là khu phố 31, phường Long Bình, tỉnh Đồng Nai).",
        ngaybh: "2025-12-09T07:32:57Z",
        hotenchv: "",
        fileqddbh: [
          {
            data: '{\n  "bucketName" : "econ-eform-demo-hn2",\n  "keyName" : "anonymous/20251209/1765265590735_File ký QDTHA chủ dộng_QT4_TH(Chánh VP_2).pdf",\n  "beanName" : "s3ClientSecond"\n}',
            name: "File ký QDTHA chủ dộng_QT4_TH(Chánh VP_2).pdf",
            size: "1.6839332580566406",
            downloadding: false,
          },
        ],
        giaoxuly: "",
        nhanlai: "",
        ticketId: "00006pyIok6BfEOwmBxAd",
        status: "dcsqttctha",
        emailtruongkvchanhvp: "binhht.dni@moj.gov.vn",
        khoan_convert:
          "Hoàn trả cho ông Tạ Hùng số tiền 300.000 đồng (Ba trăm ngàn đồng) tạm ứng án phí đã nộp theo biên lai thu số 0007410 ngày 12/6/2025 của Chi cục Thi hành án dân sự thành phố Biên Hòa, tỉnh Đồng Nai (nay là Phòng thi hành án dân sự Khu vực 1 - Đồng Nai).",
        mophongtoatk: "",
        fileguq: "",
        anphilaodongst: "",
        assigneeName: "duongpb.dni@moj.gov.vn",
        huylenhkebien: "",
        ttds_convert:
          "Ông Tạ Hùng, sinh năm 1982; Địa chỉ: 170, tổ 25, khu phố 5, phường Long Bình, thành phố Biên Hoà, tỉnh Đồng Nai (nay là khu phố 31, phường Long Bình, tỉnh Đồng Nai).",
        hotenngphaiTHA_convert: "Ông Tạ Hùng",
        duykebien: "",
        requestDate: null,
        hoten: "Ông Tạ Hùng",
        chucdanhldtha: "Phó Trưởng Thi hành án dân sự",
        truythuthue: "",
        kpthatheondba:
          "Hoàn trả cho ông Tạ Hùng số tiền 300.000 đồng (Ba trăm ngàn đồng) tạm ứng án phí đã nộp theo biên lai thu số 0007410 ngày 12/6/2025 của Chi cục Thi hành án dân sự thành phố Biên Hòa, tỉnh Đồng Nai (nay là Phòng thi hành án dân sự Khu vực 1 - Đồng Nai).",
        khat: "",
        agency: "75",
        anphichiataisan: "",
        anphilyhon: "",
        sobaqd: "109/2025/QĐST-HNGĐ",
        fileguq_convert: "",
        filedyc_convert: "",
        phongtoataisan: "",
        sdtvanthu: "0999999999",
        assigneeId: null,
        hotencbthuly: "duongpb.dni@moj.gov.vn",
        tichthusungcongvatchung: "",
        decisionNumber: " 7462/QĐ-THADS",
        hinhthucthongbao: "Thông báo qua SMS",
        tralai: "",
        lephi: "",
        noiutdi: "",
        sdtchv: "",
        signedDate: 1765265746.278066,
        filedyc: "",
        resourceType: null,
        anphihanhchinhsttrongbapt: null,
        emailcbthuly: "duongpb.dni@moj.gov.vn",
        judgmentType: "is_proactive",
        khautru: "",
        fileqd: [
          {
            data: '{\n  "bucketName" : "econ-eform-demo-hn2",\n  "keyName" : "anonymous/20251126/1764145038453_109.26.8.25 .pdf",\n  "beanName" : "s3ClientSecond"\n}',
            name: "109.26.8.25 .pdf",
            size: "0.64",
            downloadding: false,
          },
        ],
        diachikhacnguoiyc: "",
        emailcbtiepnhanqduttt: "",
        suffix: null,
        anphidsst: "",
        giaosohuu: "",
        ttbaqd:
          "Số 143/2025/QÐST-HNGĐ; ngày 22 tháng 9 năm 2025; của TÒA ÁN NHÂN DÂN KHU VỰC 1 – ĐỒNG NAI",
        emailldtha: "badn.lci@moj.gov.vn",
        noio: null,
        diachikhacnguoiyc_convert: "",
        giaosotien: "",
        huyqdthugiu: "",
        toabh: "Tòa án nhân dân khu vực 1 - Đồng Nai",
        vientro: "",
        phattien: "",
        ndcc: "Căn cứ Quyết định số 143/2025/QĐST-HNGĐ ngày 22 tháng 9 năm 2025 của Toà án nhân dân Khu vực 1 – Đồng Nai; Căn cứ Quyết định sửa chữa, bổ sung số 110/2025/QĐ-SCBSQĐ ngày 27 tháng 10 năm 2025 của Toà án nhân dân Khu vực 1 – Đồng Nai;",
        lenhkebien: "",
        sdttruongkvchanhvp: "0913171949",
        anphihspt: "",
        thuhoidat: "",
        anphihanhchinhpt: "",
        notificationEmail: "",
        areaCode: "01",
        hotenngphaiTHA: "Ông Tạ Hùng",
        notificationkhac: "",
        sdtcbthuly: "0902299401",
        fileqd_convert: [
          {
            data: '{"bucketName":"econ-eform-demo-hn2","keyName":"anonymous/20251126/1764145038453_109.26.8.25 _convert_docx.pdf","beanName":"s3ClientSecond"}',
            name: "1764145038453_109.26.8.25 _convert_docx.pdf",
            size: "0.64",
            downloadding: false,
          },
        ],
        name: "QD-THADS.109/2025/QĐST-HNGĐ.Ông Tạ Hùng",
        requester_1: "",
        sdtldtha: "0912649579",
        judgmentAndDecisionNumbers: null,
        executionRequestInfo: null,
        tenchv: null,
        xuphat: "",
        tamgiudambao: "",
        link: "https://kyta.fpt.com/thads-tracuuqd/?lookup=aYz2VcEygY",
        hotenldtha: "Đỗ Ngọc Ba",
        emailvanthu: "vanthu.dni@moj.gov.vn",
        emailchv: "",
        phongtoataikhoan: "",
        tieptuckebien: "",
        loaian: "Hôn nhân và gia đình",
        filetlkhac_convert: [
          {
            data: '{"bucketName":"econ-eform-demo-hn2","keyName":"anonymous/20251126/1764145042266_BL 7401_convert_docx.pdf","beanName":"s3ClientSecond"}',
            name: "1764145042266_BL 7401_convert_docx.pdf",
            size: "1.45",
            downloadding: false,
          },
          {
            data: '{"bucketName":"econ-eform-demo-hn2","keyName":"anonymous/20251126/1764145044740_TB 110.27.10.25_convert_docx.pdf","beanName":"s3ClientSecond"}',
            name: "1764145044740_TB 110.27.10.25_convert_docx.pdf",
            size: "0.54",
            downloadding: false,
          },
        ],
        hoantra: "",
        hotentruongkvchanhvp: "Huỳnh Thanh Bình",
        tinh: "Đồng Nai",
        hotenvanthu: "Văn thư đơn vị tỉnh Đồng Nai",
        ndcc_convert:
          "Căn cứ Quyết định số 143/2025/QĐST-HNGĐ ngày 22 tháng 9 năm 2025 của Toà án nhân dân Khu vực 1 – Đồng Nai; Căn cứ Quyết định sửa chữa, bổ sung số 110/2025/QĐ-SCBSQĐ ngày 27 tháng 10 năm 2025 của Toà án nhân dân Khu vực 1 – Đồng Nai;",
        hoanlai:
          "Hoàn lại cho ông Tạ Hùng số tiền 300.000 đồng (Ba trăm ngàn đồng) tạm ứng án phí sơ thẩm theo biên lai thu số 0007410 ngày 12/6/2025 của Chi Cục thi hành án dân sự thành phố Biên Hòa.",
        tieptuctamgiu: "",
        tichthusungcongsotien: "",
        anphicapduong: "",
        filecv_convert: "",
        filecv: "",
        dstoi: [
          ["Chương", "Mục", "Điều"],
          ["", "", ""],
          ["", "", ""],
        ],
        notificationSms: "",
        notificationsdd: "",
        qd1ghichu: "Ra quyết định",
        anphilaodongpt: "",
        huyquyetdinh: "",
        anphilaodongsttrongbapt: null,
        boithuongnn: "",
        thuhoisotien: "",
        tichthutienhuy: "",
      },
      totalMoney: 300000,
      totalReceived: 0,
      remainingAmount: 300000,
    },
    enforcementDocumentRequests: [
      {
        enforcementDocument: {
          resourceType: "attatch",
          number: "7462/QĐ-THADS",
          name: "QĐ THADS 109/2025/QĐST-HNGĐ Ông Tạ Hùng",
          releaseDate: "2025-12-09T07:35:46Z",
          submissionDate: "2025-12-05T01:44:44Z",
          page: null,
          businessType: "attach",
          documentType: "qdtha",
          status: "approved",
          resourceSystem: "eQD",
          butLuc: "1",
          deletionFlag: false,
        },
        objectStorages: [
          {
            resourceId: "judgment_decision_000061BXIg2ngtgMaB5mKx",
            fileName: "QĐ THADS 109/2025/QĐST-HNGĐ Ông Tạ Hùng",
            typeLocation: null,
            code: null,
            beanName: "s3ClientSecond",
            bucketName: "prod-2025-envelope-second",
            keyName:
              "12/completed//storage-01/5682/000062b0f2qDTQrKM6bD5iVp4a.pdf",
            documentType: "envelope",
            resourceType: "DOCUMENT_TYPE_QDTHA",
            contentType: "application/pdf",
            documentSize: 1765744,
            resourceSystem: "envelope",
            description: null,
            envelopeId: "000069bKFA4KiQrKM6bv3hVp4a",
          },
        ],
      },
      {
        enforcementDocument: {
          resourceType: "attatch",
          number: "7462/QĐ-THADS",
          name: "109.26.8.25 .pdf",
          releaseDate: "2025-12-09T07:35:46Z",
          submissionDate: "2025-12-05T01:44:44Z",
          page: null,
          businessType: "attach",
          documentType: "qdtha",
          status: "approved",
          resourceSystem: "eQD",
          butLuc: "2",
          deletionFlag: false,
        },
        objectStorages: [
          {
            resourceId: "judgment_decision_000061BXIg2ngtgMaB5mKx",
            fileName: "109.26.8.25 .pdf",
            typeLocation: null,
            code: null,
            beanName: "s3ClientSecond",
            bucketName: "econ-eform-demo-hn2",
            keyName: "anonymous/20251126/1764145038453_109.26.8.25 .pdf",
            documentType: "erequest",
            resourceType: "attatch",
            contentType: null,
            documentSize: 671088,
            resourceSystem: "eRequest",
            description: null,
            envelopeId: null,
          },
        ],
      },
      {
        enforcementDocument: {
          resourceType: "attatch",
          number: "7462/QĐ-THADS",
          name: "1764145038453_109.26.8.25 _convert_docx.pdf",
          releaseDate: "2025-12-09T07:35:46Z",
          submissionDate: "2025-12-05T01:44:44Z",
          page: null,
          businessType: "attach",
          documentType: "qdtha",
          status: "approved",
          resourceSystem: "eQD",
          butLuc: "3",
          deletionFlag: false,
        },
        objectStorages: [
          {
            resourceId: "judgment_decision_000061BXIg2ngtgMaB5mKx",
            fileName: "1764145038453_109.26.8.25 _convert_docx.pdf",
            typeLocation: null,
            code: null,
            beanName: "s3ClientSecond",
            bucketName: "econ-eform-demo-hn2",
            keyName:
              "anonymous/20251126/1764145038453_109.26.8.25 _convert_docx.pdf",
            documentType: "erequest",
            resourceType: "attatch",
            contentType: null,
            documentSize: 671088,
            resourceSystem: "eRequest",
            description: null,
            envelopeId: null,
          },
        ],
      },
      {
        enforcementDocument: {
          resourceType: "attatch",
          number: "7462/QĐ-THADS",
          name: "BL 7401.pdf",
          releaseDate: "2025-12-09T07:35:46Z",
          submissionDate: "2025-12-05T01:44:44Z",
          page: null,
          businessType: "attach",
          documentType: "qdtha",
          status: "approved",
          resourceSystem: "eQD",
          butLuc: "4",
          deletionFlag: false,
        },
        objectStorages: [
          {
            resourceId: "judgment_decision_000061BXIg2ngtgMaB5mKx",
            fileName: "BL 7401.pdf",
            typeLocation: null,
            code: null,
            beanName: "s3ClientSecond",
            bucketName: "econ-eform-demo-hn2",
            keyName: "anonymous/20251126/1764145042266_BL 7401.pdf",
            documentType: "erequest",
            resourceType: "attatch",
            contentType: null,
            documentSize: 1520435,
            resourceSystem: "eRequest",
            description: null,
            envelopeId: null,
          },
        ],
      },
      {
        enforcementDocument: {
          resourceType: "attatch",
          number: "7462/QĐ-THADS",
          name: "1764145042266_BL 7401_convert_docx.pdf",
          releaseDate: "2025-12-09T07:35:46Z",
          submissionDate: "2025-12-05T01:44:44Z",
          page: null,
          businessType: "attach",
          documentType: "qdtha",
          status: "approved",
          resourceSystem: "eQD",
          butLuc: "5",
          deletionFlag: false,
        },
        objectStorages: [
          {
            resourceId: "judgment_decision_000061BXIg2ngtgMaB5mKx",
            fileName: "1764145042266_BL 7401_convert_docx.pdf",
            typeLocation: null,
            code: null,
            beanName: "s3ClientSecond",
            bucketName: "econ-eform-demo-hn2",
            keyName:
              "anonymous/20251126/1764145042266_BL 7401_convert_docx.pdf",
            documentType: "erequest",
            resourceType: "attatch",
            contentType: null,
            documentSize: 1520435,
            resourceSystem: "eRequest",
            description: null,
            envelopeId: null,
          },
        ],
      },
      {
        enforcementDocument: {
          resourceType: "attatch",
          number: "7462/QĐ-THADS",
          name: "TB 110.27.10.25.pdf",
          releaseDate: "2025-12-09T07:35:46Z",
          submissionDate: "2025-12-05T01:44:44Z",
          page: null,
          businessType: "attach",
          documentType: "qdtha",
          status: "approved",
          resourceSystem: "eQD",
          butLuc: "6",
          deletionFlag: false,
        },
        objectStorages: [
          {
            resourceId: "judgment_decision_000061BXIg2ngtgMaB5mKx",
            fileName: "TB 110.27.10.25.pdf",
            typeLocation: null,
            code: null,
            beanName: "s3ClientSecond",
            bucketName: "econ-eform-demo-hn2",
            keyName: "anonymous/20251126/1764145044740_TB 110.27.10.25.pdf",
            documentType: "erequest",
            resourceType: "attatch",
            contentType: null,
            documentSize: 566231,
            resourceSystem: "eRequest",
            description: null,
            envelopeId: null,
          },
        ],
      },
      {
        enforcementDocument: {
          resourceType: "attatch",
          number: "7462/QĐ-THADS",
          name: "1764145044740_TB 110.27.10.25_convert_docx.pdf",
          releaseDate: "2025-12-09T07:35:46Z",
          submissionDate: "2025-12-05T01:44:44Z",
          page: null,
          businessType: "attach",
          documentType: "qdtha",
          status: "approved",
          resourceSystem: "eQD",
          butLuc: "7",
          deletionFlag: false,
        },
        objectStorages: [
          {
            resourceId: "judgment_decision_000061BXIg2ngtgMaB5mKx",
            fileName: "1764145044740_TB 110.27.10.25_convert_docx.pdf",
            typeLocation: null,
            code: null,
            beanName: "s3ClientSecond",
            bucketName: "econ-eform-demo-hn2",
            keyName:
              "anonymous/20251126/1764145044740_TB 110.27.10.25_convert_docx.pdf",
            documentType: "erequest",
            resourceType: "attatch",
            contentType: null,
            documentSize: 566231,
            resourceSystem: "eRequest",
            description: null,
            envelopeId: null,
          },
        ],
      },
      {
        enforcementDocument: {
          resourceType: "attatch",
          number: "7462/QĐ-THADS",
          name: "File ký QDTHA chủ dộng_QT4_TH(Chánh VP_2).pdf",
          releaseDate: "2025-12-09T07:35:46Z",
          submissionDate: "2025-12-05T01:44:44Z",
          page: null,
          businessType: "attach",
          documentType: "qdtha",
          status: "approved",
          resourceSystem: "eQD",
          butLuc: "8",
          deletionFlag: false,
        },
        objectStorages: [
          {
            resourceId: "judgment_decision_000061BXIg2ngtgMaB5mKx",
            fileName: "File ký QDTHA chủ dộng_QT4_TH(Chánh VP_2).pdf",
            typeLocation: null,
            code: null,
            beanName: "s3ClientSecond",
            bucketName: "econ-eform-demo-hn2",
            keyName:
              "anonymous/20251209/1765265590735_File ký QDTHA chủ dộng_QT4_TH(Chánh VP_2).pdf",
            documentType: "erequest",
            resourceType: "attatch",
            contentType: null,
            documentSize: 1765732,
            resourceSystem: "eRequest",
            description: null,
            envelopeId: null,
          },
        ],
      },
    ],
    enforcementParties: [
      {
        name: "Tạ Hùng",
        type: "P",
        attrs: {
          dob: null,
          ma_xa: null,
          ma_tinh: null,
          quoc_tich: null,
          represent: null,
          chuc_danh_dai_dien: null,
        },
        email: null,
        gender: null,
        birthDay: "1982",
        subjects: "ndtha",
        description: null,
        phoneNumber: null,
        deletionFlag: false,
        identification: null,
        permanentAddress:
          "170, tổ 25, khu phố 5, phường Long Bình, thành phố Biên Hoà, tỉnh Đồng Nai (nay là khu phố 31, phường Long Bình, tỉnh Đồng Nai).",
        temporaryAddress:
          "170, tổ 25, khu phố 5, phường Long Bình, thành phố Biên Hoà, tỉnh Đồng Nai (nay là khu phố 31, phường Long Bình, tỉnh Đồng Nai).",
      },
      {
        name: "Chi cục Thi hành án dân sự thành phố Biên Hòa, tỉnh Đồng Nai (nay là Phòng thi hành án dân sự Khu vực 1 - Đồng Nai).",
        type: "O",
        attrs: {
          dob: null,
          ma_xa: null,
          ma_tinh: null,
          quoc_tich: null,
          represent: null,
          chuc_danh_dai_dien: null,
        },
        email: null,
        gender: null,
        birthDay: null,
        subjects: "nptha",
        description: null,
        phoneNumber: null,
        deletionFlag: false,
        identification: null,
        permanentAddress: null,
        temporaryAddress: null,
      },
    ],
    businessOperationDetails: [
      {
        note: null,
        paid: 0,
        rest: 300000,
        type: "tra_tien",
        attrs: {
          currency: "VND",
        },
        issue: null,
        money: 300000,
        exempt: null,
        period: "thongbaoquyetdinhtha",
        reason: null,
        reduce: null,
        status: "dangthihanh",
        addition: null,
        assetType: null,
        description: "tạm ứng án phí đã nộp",
        obligorName: {
          html: "Chi cục Thi hành án dân sự thành phố Biên Hòa, tỉnh Đồng Nai (nay là Phòng thi hành án dân sự Khu vực 1 - Đồng Nai).",
          base64: null,
        },
        postponedTo: null,
        businessType: "financial",
        personalInfos: null,
        postponedFrom: null,
        processingType: null,
        donvinhanutxlts: null,
        idhosonhanUTXLTS: null,
        relatedBusinessId: null,
        emailchvnhanUTXLTS: null,
        obligorName: {
          html: "Tạ Hùng",
          base64: null,
        },
      },
    ],
  },
  {
    enforcement: {
      attrs: {
        sobanan: "31/QĐST-DS",
        qd1loai: "Dân sự",
        ngaybanan: "2025-07-08T17:00:00Z",
        toaan: "Thi hành án dân sự thành phố Hồ Chí Minh",
      },
      decisionId: "000061DzI1WDDSxDGxXyyO",
      decisionNumber: "25328/QĐ-THADS",
      requestDate: "2025-12-11T11:01:46Z",
      type: "is_proactive",
      contentRequirements: {
        base64: null,
        html: "Hoàn lại cho Ngân hàng TMCP Đầu tư và Phát Triển Việt Nam (BIDV) số tiền tạm ứng án phí 19.477.000 đồng (Mười chín triệu bốn trăm bảy mươi bảy nghìn đồng) do Ngân hàng TMCP Đầu tư và Phát triển Việt Nam (BIDV) đã nộp theo biên lai thu tiền số 0063948 ngày 19/3/2025 của Chi cục Thi hành án dân sự huyện Củ Chi, Thành phố Hồ Chí Minh (sau sáp nhập là Thi hành án dân sự Thành phố Hồ Chí Minh).",
      },
      propertyInfo: {
        base64: null,
        html: null,
      },
      requester: null,
      requesterId: null,
      requesterAddress: null,
      enforcementAgency: "Thi hành án dân sự thành phố Hồ Chí Minh",
      status: "dangthihanh",
      period: "thongbaoquyetdinhtha",
      action: "RA_QUYET_DINH",
      assigneeName: "diempth.hcm@moj.gov.vn",
      assignee: "test_candv.hcm@moj.gov.vn",
      preAssignee: null,
      ticketId: "000065yI4gq1Hgepgz4aJ",
      envelopeId: null,
      judgmentInfo: {
        base64: null,
        html: "Căn cứ Quyết định công nhận sự thỏa thuận của các đương sự số 31/2025/QĐST-DS ngày 09 tháng 7 năm 2025 của Tòa án nhân dân Khu vực 8 - Thành phố Hồ Chí Minh; Căn cứ Thông báo sửa chữa bổ sung quyết định số 34/2025/TB-TA ngày 03 tháng 9 năm 2025 của Tòa án nhân dân Khu vực 8 - Thành phố Hồ Chí Minh.",
      },
      obligorName: {
        base64: null,
        html: "Ngân hàng TMCP Đầu tư và Phát triển Việt Nam (BIDV), địa chỉ: Tháp BIDV, Số 194 Trần Quang Khải, phường Lý Thái Tổ, quận Hoàn Kiếm, thành phố Hà Nội (nay là phường Hoàn Kiếm, thành phố Hà Nội). Địa chỉ liên lạc: Số 216-218, Tỉnh lộ 8, xã Tân An Hội (thị trấn Củ Chi, huyện Củ Chi cũ), Thành phố Hồ Chí Minh).",
      },
      lookup: null,
      receivedDate: "2025-12-05T16:35:33Z",
      signedDate: "2025-12-08T06:38:00Z",
      rawData: {
        requester_goc: "",
        judgmentInfo:
          "Căn cứ Quyết định công nhận sự thỏa thuận của các đương sự số 31/2025/QĐST-DS ngày 09 tháng 7 năm 2025 của Tòa án nhân dân Khu vực 8 - Thành phố Hồ Chí Minh; Căn cứ Thông báo sửa chữa bổ sung quyết định số 34/2025/TB-TA ngày 03 tháng 9 năm 2025 của Tòa án nhân dân Khu vực 8 - Thành phố Hồ Chí Minh.",
        anphihsst: "",
        kpthatheokhoan:
          "Ngân hàng Thương mại Cổ phần Đầu tư và Phát triển Việt Nam có quyền yêu cầu Cơ quan Thi hành án dân sự có thẩm quyền phát mãi tài sản thế chấp để đảm bảo thi hành án, cụ thể là thửa đất số 324, tờ bản đồ số 4, địa chỉ: 321 Nguyễn Sơn, phường Phú Thạnh, quận Tân Phú, Thành phố Hồ Chí Minh theo Giấy chứng nhận quyền sử dụng đất, quyền sở hữu nhà ở và tài sản khác gắn liền với đất số BĐ 119696, số vào sổ cấp GCN: CH 08573, do UBND quận Tân Phú cấp ngày 04/10/2010 cho ông Nguyễn Tấn Việt. Tài sản nêu trên được thế chấp theo Hợp đồng thế chấp tài sản số: 01/2022/17762205/HĐBĐ ngày 16/8/2022, công chứng tại phòng công chứng Mai Việt Cường, Thành phố Hồ Chí Minh. Địa chỉ: Số 236 Cao Thắng, phường 12, quận 10, thành phố Hồ Chí Minh, số công chứng 018809, quyển số 08/2022 TP/CC-SCC/HĐGD ngày 16/8/2022, đăng ký giao dịch bảo đảm tại – Chi nhánh Văn phòng đăng ký đất đai quận Tân Phú ngày 19/8/2022 và Hợp đồng sửa đổi, bổ sung Hợp đồng thế chấp bất động sản số 01/2022/17762205/HĐBĐ ngày 16/8/2022, công chứng tại phòng công chứng Mai Việt Cường, Thành phố Hồ Chí Minh. Địa chỉ: Số 236 Cao Thắng, phường 12, quận 10, Thành phố Hồ Chí Minh, số công chứng 014885, quyển số 09/2023 TP/CC-SCC/HĐGD. Hoàn lại cho Ngân hàng TMCP Đầu tư và Phát Triển Việt Nam (BIDV) số tiền tạm ứng án phí 19.477.000₫ (Mười chín triệu bốn trăm bảy mươi bảy nghìn đồng) do Ngân hàng TMCP Đầu tư và Phát triển Việt Nam (BIDV) đã nộp theo biên lai thu tiền số 0063948 ngày 19/3/2025 của Chi cục Thi hành án dân sự huyện Củ Chi, Thành phố Hồ Chí Minh.",
        type: "",
        anphihanhchinhst: "",
        dchingphaiTHA_convert:
          "Tháp BIDV, số 194 Trần Quang Khải, phường Lý Thái Tổ, quận Hoàn Kiếm, Thành phố Hà Nội",
        rejectCode: null,
        requesterName: null,
        diachithuongtrunguoiyc_convert: "",
        xacnhan: "",
        cqbh: "THI HÀNH ÁN DÂN SỰ THÀNH PHỐ HỒ CHÍ MINH",
        ghinhan: "",
        truythu: "",
        requester: "",
        qr: "https://prod-2025-thads-qdtha-attachment-hn2.s3-han02.fptcloud.com/12/5682/qr/000061DzI1WDDSxDGxXyyO/1765162688572/000061DzI1WDDSxDGxXyyO.png",
        requesterId: "",
        "10d": "Không",
        notificationPost: "",
        anphidspt: "",
        dchingphaiTHA:
          "Tháp BIDV, số 194 Trần Quang Khải, phường Lý Thái Tổ, quận Hoàn Kiếm, Thành phố Hà Nội",
        diachi:
          "Tháp BIDV, số 194 Trần Quang Khải, phường Lý Thái Tổ, quận Hoàn Kiếm, Thành phố Hà Nội",
        hotencbtiepnhanqduttt: "",
        sdtcbtiepnhanqduttt: "",
        khuvucxlan: "",
        diachithuongtrunguoiyc: "",
        ttds: "Ngân hàng TMCP Đầu tư và Phát triển Việt Nam (BIDV), địa chỉ: Tháp BIDV, Số 194 Trần Quang Khải, phường Lý Thái Tổ, quận Hoàn Kiếm, thành phố Hà Nội (nay là phường Hoàn Kiếm, thành phố Hà Nội). Địa chỉ liên lạc: Số 216-218, Tỉnh lộ 8, xã Tân An Hội (thị trấn Củ Chi, huyện Củ Chi cũ), Thành phố Hồ Chí Minh).",
        ngaybh: "2025-12-08T06:37:44Z",
        hotenchv: "",
        fileqddbh: [
          {
            data: '{\n  "bucketName" : "econ-eform-demo-hn2",\n  "keyName" : "anonymous/20251208/1765175869346_File ký QDTHA chủ dộng_QT4_TH(Chánh VP_2).pdf",\n  "beanName" : "s3ClientSecond"\n}',
            name: "File ký QDTHA chủ dộng_QT4_TH(Chánh VP_2).pdf",
            size: "1.678487777709961",
            downloadding: false,
          },
        ],
        giaoxuly: "",
        nhanlai: "",
        ticketId: "000065yI4gq1Hgepgz4aJ",
        status: "dcsqttctha",
        emailtruongkvchanhvp: "vupn.hcm@moj.gov.vn",
        khoan_convert:
          "Hoàn lại cho Ngân hàng TMCP Đầu tư và Phát Triển Việt Nam (BIDV) số tiền tạm ứng án phí 19.477.000 đồng (Mười chín triệu bốn trăm bảy mươi bảy nghìn đồng) do Ngân hàng TMCP Đầu tư và Phát triển Việt Nam (BIDV) đã nộp theo biên lai thu tiền số 0063948 ngày 19/3/2025 của Chi cục Thi hành án dân sự huyện Củ Chi, Thành phố Hồ Chí Minh (sau sáp nhập là Thi hành án dân sự Thành phố Hồ Chí Minh).",
        mophongtoatk: "",
        fileguq: "",
        anphilaodongst: "",
        assigneeName: "diempth.hcm@moj.gov.vn",
        huylenhkebien: "",
        ttds_convert:
          "Ngân hàng TMCP Đầu tư và Phát triển Việt Nam (BIDV), địa chỉ: Tháp BIDV, Số 194 Trần Quang Khải, phường Lý Thái Tổ, quận Hoàn Kiếm, thành phố Hà Nội (nay là phường Hoàn Kiếm, thành phố Hà Nội). Địa chỉ liên lạc: Số 216-218, Tỉnh lộ 8, xã Tân An Hội (thị trấn Củ Chi, huyện Củ Chi cũ), Thành phố Hồ Chí Minh).",
        hotenngphaiTHA_convert:
          "Ngân hàng TMCP Đầu tư và Phát triển Việt Nam (BIDV)",
        duykebien: "",
        requestDate: null,
        hoten: "Ngân hàng TMCP Đầu tư và Phát triển Việt Nam (BIDV)",
        chucdanhldtha: "Phó Trưởng Thi hành án dân sự",
        truythuthue: "",
        kpthatheondba:
          "Hoàn lại cho Ngân hàng TMCP Đầu tư và Phát Triển Việt Nam (BIDV) số tiền tạm ứng án phí 19.477.000 đồng (Mười chín triệu bốn trăm bảy mươi bảy nghìn đồng) do Ngân hàng TMCP Đầu tư và Phát triển Việt Nam (BIDV) đã nộp theo biên lai thu tiền số 0063948 ngày 19/3/2025 của Chi cục Thi hành án dân sự huyện Củ Chi, Thành phố Hồ Chí Minh (sau sáp nhập là Thi hành án dân sự Thành phố Hồ Chí Minh).",
        khat: "",
        agency: "79",
        anphichiataisan: "",
        anphilyhon: "",
        sobaqd: "31/QĐST-DS",
        fileguq_convert: "",
        filedyc_convert: "",
        phongtoataisan: "",
        sdtvanthu: "0999999999",
        assigneeId: null,
        hotencbthuly: "diempth.hcm@moj.gov.vn",
        tichthusungcongvatchung: "",
        decisionNumber: " 25328/QĐ-THADS",
        hinhthucthongbao: "Thông báo qua SMS",
        tralai: "",
        lephi: "",
        noiutdi: "",
        sdtchv: "",
        signedDate: 1765175880.046058,
        filedyc: "",
        resourceType: null,
        anphihanhchinhsttrongbapt: null,
        emailcbthuly: "diempth.hcm@moj.gov.vn",
        judgmentType: "is_proactive",
        khautru: "",
        diachikhacnguoiyc: "",
        emailcbtiepnhanqduttt: "",
        suffix: null,
        anphidsst: "",
        giaosohuu: "",
        ttbaqd:
          "Số 31/2025/QĐST-DS; 09 tháng 7 năm 2025; của TÒA ÁN NHÂN DÂN KHU VỰC 8 THÀNH PHỐ HỒ CHÍ MINH",
        emailldtha: "hongtp.hcm@moj.gov.vn",
        noio: null,
        diachikhacnguoiyc_convert: "",
        giaosotien: "",
        huyqdthugiu: "",
        toabh: "Tòa án nhân dân khu vực 8 - Hồ Chí Minh",
        vientro: "",
        phattien: "",
        ndcc: "Căn cứ Quyết định công nhận sự thỏa thuận của các đương sự số 31/2025/QĐST-DS ngày 09 tháng 7 năm 2025 của Tòa án nhân dân Khu vực 8 - Thành phố Hồ Chí Minh; Căn cứ Thông báo sửa chữa bổ sung quyết định số 34/2025/TB-TA ngày 03 tháng 9 năm 2025 của Tòa án nhân dân Khu vực 8 - Thành phố Hồ Chí Minh.",
        lenhkebien: "",
        sdttruongkvchanhvp: "0918384614",
        anphihspt: "",
        thuhoidat: "",
        anphihanhchinhpt: "",
        notificationEmail: "",
        areaCode: "08",
        hotenngphaiTHA: "Ngân hàng TMCP Đầu tư và Phát triển Việt Nam (BIDV)",
        notificationkhac: "",
        sdtcbthuly: "0999999999",
        name: "QD-THADS.31/QĐST-DS.Ngân hàng TMCP Đầu tư và Phát triển Việt Nam (BIDV)",
        requester_1: "",
        sdtldtha: "0971591611",
        judgmentAndDecisionNumbers: null,
        executionRequestInfo: null,
        tenchv: null,
        filest_convert: [
          {
            data: '{"bucketName":"econ-eform-demo-hn2","keyName":"anonymous/20251203/1764767475659_QĐ 31 ngày 09.7.2025_convert_docx.pdf","beanName":"s3ClientSecond"}',
            name: "1764767475659_QĐ 31 ngày 09.7.2025_convert_docx.pdf",
            size: "1.66",
            downloadding: false,
          },
        ],
        xuphat: "",
        tamgiudambao: "",
        link: "https://kyta.fpt.com/thads-tracuuqd/?lookup=p74eph1R1Z",
        hotenldtha: "Trần Phương Hồng",
        emailvanthu: "vanthu.hcm@moj.gov.vn",
        emailchv: "quynhltn.hcm@moj.gov.vn",
        phongtoataikhoan: "",
        tieptuckebien: "",
        loaian: "Dân sự",
        hoantra: "",
        filest: [
          {
            data: '{\n  "bucketName" : "econ-eform-demo-hn2",\n  "keyName" : "anonymous/20251203/1764767475659_QĐ 31 ngày 09.7.2025.pdf",\n  "beanName" : "s3ClientSecond"\n}',
            name: "QĐ 31 ngày 09.7.2025.pdf",
            size: "1.66",
            downloadding: false,
          },
        ],
        hotentruongkvchanhvp: "Phạm Ngọc Vũ",
        tinh: "Thành phố Hồ Chí Minh",
        hotenvanthu: "Văn thư đơn vị TP Hồ Chí Minh",
        ndcc_convert:
          "Căn cứ Quyết định công nhận sự thỏa thuận của các đương sự số 31/2025/QĐST-DS ngày 09 tháng 7 năm 2025 của Tòa án nhân dân Khu vực 8 - Thành phố Hồ Chí Minh; Căn cứ Thông báo sửa chữa bổ sung quyết định số 34/2025/TB-TA ngày 03 tháng 9 năm 2025 của Tòa án nhân dân Khu vực 8 - Thành phố Hồ Chí Minh.",
        hoanlai:
          "Hoàn lại cho Ngân hàng TMCP Đầu tư và Phát Triển Việt Nam (BIDV) số tiền tạm ứng án phí 19.477.000₫ (Mười chín triệu bốn trăm bảy mươi bảy nghìn đồng) do Ngân hàng TMCP Đầu tư và Phát triển Việt Nam (BIDV) đã nộp theo biên lai thu tiền số 0063948 ngày 19/3/2025 của Chi cục Thi hành án dân sự huyện Củ Chi, Thành phố Hồ Chí Minh.",
        tieptuctamgiu: "",
        tichthusungcongsotien: "",
        anphicapduong: "",
        filecv_convert: "",
        filecv: "",
        dstoi: [
          ["Chương", "Mục", "Điều"],
          ["", "", ""],
          ["", "", ""],
        ],
        notificationSms: "",
        notificationsdd: "",
        qd1ghichu: "Ra quyết định",
        anphilaodongpt: "",
        huyquyetdinh: "",
        anphilaodongsttrongbapt: null,
        boithuongnn: "",
        thuhoisotien: "",
        tichthutienhuy: "",
      },
      totalMoney: 19477000,
      totalReceived: 0,
      remainingAmount: 19477000,
    },
    enforcementDocumentRequests: [
      {
        enforcementDocument: {
          resourceType: "attatch",
          number: "25328/QĐ-THADS",
          name: "QĐ THADS 31/QĐST-DS Ngân hàng TMCP Đầu tư và Phát triển Việt Nam (BIDV)",
          releaseDate: "2025-12-08T06:38:00Z",
          submissionDate: "2025-12-05T16:35:33Z",
          page: null,
          businessType: "attach",
          documentType: "qdtha",
          status: "approved",
          resourceSystem: "eQD",
          butLuc: "1",
          deletionFlag: false,
        },
        objectStorages: [
          {
            resourceId: "judgment_decision_000061DzI1WDDSxDGxXyyO",
            fileName:
              "QĐ THADS 31/QĐST-DS Ngân hàng TMCP Đầu tư và Phát triển Việt Nam (BIDV)",
            typeLocation: null,
            code: null,
            beanName: "s3ClientSecond",
            bucketName: "prod-2025-envelope-second",
            keyName:
              "12/completed//storage-01/5682/0000617XOHr1MivexW9J1zH9k9r.pdf",
            documentType: "envelope",
            resourceType: "DOCUMENT_TYPE_QDTHA",
            contentType: "application/pdf",
            documentSize: 1760032,
            resourceSystem: "envelope",
            description: null,
            envelopeId: "00006049iNglSd2gE8mRQf3a3N",
          },
        ],
      },
      {
        enforcementDocument: {
          resourceType: "attatch",
          number: "25328/QĐ-THADS",
          name: "QĐ 31 ngày 09.7.2025.pdf",
          releaseDate: "2025-12-08T06:38:00Z",
          submissionDate: "2025-12-05T16:35:33Z",
          page: null,
          businessType: "attach",
          documentType: "qdtha",
          status: "approved",
          resourceSystem: "eQD",
          butLuc: "2",
          deletionFlag: false,
        },
        objectStorages: [
          {
            resourceId: "judgment_decision_000061DzI1WDDSxDGxXyyO",
            fileName: "QĐ 31 ngày 09.7.2025.pdf",
            typeLocation: null,
            code: null,
            beanName: "s3ClientSecond",
            bucketName: "econ-eform-demo-hn2",
            keyName:
              "anonymous/20251203/1764767475659_QĐ 31 ngày 09.7.2025.pdf",
            documentType: "erequest",
            resourceType: "attatch",
            contentType: null,
            documentSize: 1740636,
            resourceSystem: "eRequest",
            description: null,
            envelopeId: null,
          },
        ],
      },
      {
        enforcementDocument: {
          resourceType: "attatch",
          number: "25328/QĐ-THADS",
          name: "1764767475659_QĐ 31 ngày 09.7.2025_convert_docx.pdf",
          releaseDate: "2025-12-08T06:38:00Z",
          submissionDate: "2025-12-05T16:35:33Z",
          page: null,
          businessType: "attach",
          documentType: "qdtha",
          status: "approved",
          resourceSystem: "eQD",
          butLuc: "3",
          deletionFlag: false,
        },
        objectStorages: [
          {
            resourceId: "judgment_decision_000061DzI1WDDSxDGxXyyO",
            fileName: "1764767475659_QĐ 31 ngày 09.7.2025_convert_docx.pdf",
            typeLocation: null,
            code: null,
            beanName: "s3ClientSecond",
            bucketName: "econ-eform-demo-hn2",
            keyName:
              "anonymous/20251203/1764767475659_QĐ 31 ngày 09.7.2025_convert_docx.pdf",
            documentType: "erequest",
            resourceType: "attatch",
            contentType: null,
            documentSize: 1740636,
            resourceSystem: "eRequest",
            description: null,
            envelopeId: null,
          },
        ],
      },
    ],
    enforcementParties: [
      {
        name: "Ngân hàng TMCP Đầu tư và Phát triển Việt Nam (BIDV)",
        type: "O",
        attrs: {
          dob: null,
          ma_xa: null,
          ma_tinh: null,
          quoc_tich: null,
          represent: null,
          chuc_danh_dai_dien: null,
        },
        email: null,
        gender: null,
        birthDay: null,
        subjects: "ndtha",
        description: null,
        phoneNumber: null,
        deletionFlag: false,
        identification: null,
        permanentAddress:
          "Tháp BIDV, Số 194 Trần Quang Khải, phường Lý Thái Tổ, quận Hoàn Kiếm, thành phố Hà Nội (nay là phường Hoàn Kiếm, thành phố Hà Nội)",
        temporaryAddress:
          "Số 216-218, Tỉnh lộ 8, xã Tân An Hội (thị trấn Củ Chi, huyện Củ Chi cũ), Thành phố Hồ Chí Minh",
      },
      {
        name: "Chi cục Thi hành án dân sự huyện Củ Chi",
        type: "O",
        attrs: {
          dob: null,
          ma_xa: null,
          ma_tinh: null,
          quoc_tich: null,
          represent: null,
          chuc_danh_dai_dien: null,
        },
        email: null,
        gender: null,
        birthDay: null,
        subjects: "nptha",
        description: null,
        phoneNumber: null,
        deletionFlag: false,
        identification: null,
        permanentAddress: null,
        temporaryAddress: null,
      },
    ],
    businessOperationDetails: [
      {
        note: null,
        paid: 0,
        rest: 19477000,
        type: "tra_tien",
        attrs: {
          currency: "VND",
        },
        issue: null,
        money: 19477000,
        exempt: null,
        period: "thongbaoquyetdinhtha",
        reason: null,
        reduce: null,
        status: "dangthihanh",
        addition: null,
        assetType: null,
        description: "số tiền tạm ứng án phí",
        obligorName: {
          html: "Chi cục Thi hành án dân sự huyện Củ Chi",
          base64: null,
        },
        postponedTo: null,
        businessType: "financial",
        personalInfos: null,
        postponedFrom: null,
        processingType: null,
        donvinhanutxlts: null,
        idhosonhanUTXLTS: null,
        relatedBusinessId: null,
        emailchvnhanUTXLTS: null,
        obligorName: {
          html: "Ngân hàng TMCP Đầu tư và Phát triển Việt Nam (BIDV)",
          base64: null,
        },
      },
    ],
  },
  {
    enforcement: {
      attrs: {
        sobanan: "21/2025/QĐST-DS",
        qd1loai: "Dân sự",
        ngaybanan: "2025-11-04T17:00:00Z",
        toaan: "Thi hành án dân sự thành phố Đà Nẵng",
      },
      decisionId: "000061OWIqlnQsJpKEEgRx",
      decisionNumber: "5576/QĐ-THADS",
      requestDate: "2025-12-09T07:58:49Z",
      type: "is_proactive",
      contentRequirements: {
        base64: null,
        html: "Sung ngân sách nhà nước số tiền tạm ứng lệ phí ông Hốih Thông đã nộp là 300.000 (ba trăm nghìn đồng) theo Biên lai thu tiền thuế, phí, lệ phí Tòa án số 0003194 ngày 17 tháng 10 năm 2025 của Thi hành án dân sự thành phố Đà Nẵng.",
      },
      propertyInfo: {
        base64: null,
        html: null,
      },
      requester: null,
      requesterId: null,
      requesterAddress: null,
      enforcementAgency: "Thi hành án dân sự thành phố Đà Nẵng",
      status: "dangthihanh",
      period: "thongbaoquyetdinhtha",
      action: "RA_QUYET_DINH",
      assigneeName: "thuyvtt.qnm@moj.gov.vn",
      assignee: "test_candv.hcm@moj.gov.vn",
      preAssignee: null,
      ticketId: "00006yMIDOKdt5EneeOPJ",
      envelopeId: null,
      judgmentInfo: {
        base64: null,
        html: "Căn cứ Quyết định số 21/2025/QĐST-DS ngày 05 tháng 11 năm 2025 của Tòa án nhân dân Khu vực 12 - Đà Nẵng.",
      },
      obligorName: {
        base64: null,
        html: "Hốih Thông, sinh năm 1996, địa chỉ: Thôn Aró, xã Tây Giang, thành phố Đà Nẵng.",
      },
      lookup: null,
      receivedDate: "2025-12-09T07:58:38Z",
      signedDate: "2025-12-11T02:03:53Z",
      rawData: {
        requester_goc: "",
        judgmentInfo:
          "Căn cứ Quyết định số 21/2025/QĐST-DS ngày 05 tháng 11 năm 2025 của Tòa án nhân dân Khu vực 12 - Đà Nẵng.",
        anphihsst: "",
        kpthatheokhoan:
          "Sung ngân sách nhà nước số tiền tạm ứng lệ phí ông Hốih Thông đã nộp là 300.000 (ba trăm nghìn) đồng theo biên lai thu tiền thuế, phí, lệ phí Tòa án số 0003194 ngày 17 tháng 10 năm 2025 của Thi hành án dân sự thành phố Đà Nẵng.",
        type: "",
        filetlkhac: null,
        anphihanhchinhst: "",
        dchingphaiTHA_convert: "Thôn Aró, xã Tây Giang, thành phố Đà Nẵng",
        filegdt_convert: null,
        diachithuongtrunguoiyc_convert: "",
        xacnhan: "",
        cqbh: "THI HÀNH ÁN DÂN SỰ THÀNH PHỐ ĐÀ NẴNG",
        ghinhan: "",
        truythu: "",
        requester: "",
        qr: "https://prod-2025-thads-qdtha-attachment-hn2.s3-han02.fptcloud.com/12/5682/qr/000061OWIqlnQsJpKEEgRx/1765268489216/000061OWIqlnQsJpKEEgRx.png",
        requesterId: "",
        "10d": "Không",
        notificationPost: "",
        anphidspt: "",
        dchingphaiTHA: "Thôn Aró, xã Tây Giang, thành phố Đà Nẵng",
        diachi: "Thôn Aró, xã Tây Giang, thành phố Đà Nẵng",
        hotencbtiepnhanqduttt: "",
        filegdt: null,
        sdtcbtiepnhanqduttt: "",
        khuvucxlan: "",
        diachithuongtrunguoiyc: "",
        ttds: "Hốih Thông, sinh năm 1996, địa chỉ: Thôn Aró, xã Tây Giang, thành phố Đà Nẵng.",
        ngaybh: "2025-12-11T02:02:42Z",
        hotenchv: "",
        fileqddbh: [
          {
            data: '{\n  "bucketName" : "econ-eform-demo-hn2",\n  "keyName" : "anonymous/20251211/1765418568902_File ký QDTHA chủ dộng_QT4_TH(Chánh VP_2).pdf",\n  "beanName" : "s3ClientSecond"\n}',
            name: "File ký QDTHA chủ dộng_QT4_TH(Chánh VP_2).pdf",
            size: "1.6581668853759766",
            downloadding: false,
          },
        ],
        giaoxuly: "",
        nhanlai: "",
        ticketId: "00006yMIDOKdt5EneeOPJ",
        status: "cph_qdthacd",
        emailtruongkvchanhvp: "thuantn.qnm@moj.gov.vn",
        filept_convert: null,
        khoan_convert:
          "Sung ngân sách nhà nước số tiền tạm ứng lệ phí ông Hốih Thông đã nộp là 300.000 (ba trăm nghìn đồng) theo Biên lai thu tiền thuế, phí, lệ phí Tòa án số 0003194 ngày 17 tháng 10 năm 2025 của Thi hành án dân sự thành phố Đà Nẵng.",
        mophongtoatk: "",
        fileguq: "",
        legalRepresentative: null,
        anphilaodongst: "",
        assigneeName: "thuyvtt.qnm@moj.gov.vn",
        huylenhkebien: "",
        ttds_convert:
          "Hốih Thông, sinh năm 1996, địa chỉ: Thôn Aró, xã Tây Giang, thành phố Đà Nẵng.",
        hotenngphaiTHA_convert: "Ông Hốih Thông",
        duykebien: "",
        hoten: "Ông Hốih Thông",
        chucdanhldtha: "Phó Trưởng Thi hành án dân sự",
        truythuthue: "",
        kpthatheondba:
          "Sung ngân sách nhà nước số tiền tạm ứng lệ phí ông Hốih Thông đã nộp là 300.000 (ba trăm nghìn đồng) theo Biên lai thu tiền thuế, phí, lệ phí Tòa án số 0003194 ngày 17 tháng 10 năm 2025 của Thi hành án dân sự thành phố Đà Nẵng.",
        khat: "",
        agency: "48",
        anphichiataisan: "",
        anphilyhon: "",
        sobaqd: "21/2025/QĐST-DS",
        fileguq_convert: "",
        filedyc_convert: "",
        phongtoataisan: "",
        sdtvanthu: "0999999999",
        hotencbthuly: "thuyvtt.qnm@moj.gov.vn",
        tichthusungcongvatchung: "",
        decisionNumber: " 5576/QĐ-THADS",
        hinhthucthongbao: "Thông báo qua SMS",
        tralai: "",
        lephi:
          "Sung ngân sách nhà nước số tiền tạm ứng lệ phí ông Hốih Thông đã nộp là 300.000 (ba trăm nghìn) đồng theo biên lai thu tiền thuế, phí, lệ phí Tòa án số 0003194 ngày 17 tháng 10 năm 2025 của Thi hành án dân sự thành phố Đà Nẵng.",
        noiutdi: "",
        sdtchv: "",
        signedDate: 1765418633.9075005,
        filedyc: "",
        emailcbthuly: "thuyvtt.qnm@moj.gov.vn",
        judgmentType: "is_proactive",
        khautru: "",
        fileqd: [
          {
            data: '{\n  "bucketName" : "econ-eform-demo-hn2",\n  "keyName" : "anonymous/20251209/1765264122801_21. DSST. Hốih Thông.pdf",\n  "beanName" : "s3ClientSecond"\n}',
            name: "21. DSST. Hốih Thông.pdf",
            size: "0.66",
            downloadding: false,
          },
        ],
        filept: null,
        diachikhacnguoiyc: "",
        emailcbtiepnhanqduttt: "",
        anphidsst: "",
        giaosohuu: "",
        ttbaqd:
          "Số 21/2025/QĐST-DS; ngày 05 tháng 11 năm 2025; của TOÀ ÁN NHÂN DÂN KHU VỰC 12 - ĐÀ NẴNG",
        emailldtha: "donghm.qnm@moj.gov.vn",
        diachikhacnguoiyc_convert: "",
        giaosotien: "",
        huyqdthugiu: "",
        toabh: "Tòa án nhân dân khu vực 12 - Đà Nẵng",
        vientro: "",
        phattien: "",
        ndcc: "Căn cứ Quyết định số 21/2025/QĐST-DS ngày 05 tháng 11 năm 2025 của Tòa án nhân dân Khu vực 12 - Đà Nẵng.",
        lenhkebien: "",
        sdttruongkvchanhvp: "0905503379",
        filett_convert: null,
        anphihspt: "",
        thuhoidat: "",
        anphihanhchinhpt: "",
        notificationEmail: "",
        areaCode: "12",
        hotenngphaiTHA: "Ông Hốih Thông",
        notificationkhac: "",
        sdtcbthuly: "0911651559",
        fileqd_convert: [
          {
            data: '{"bucketName":"econ-eform-demo-hn2","keyName":"anonymous/20251209/1765264122801_21. DSST. Hốih Thông_convert_docx.pdf","beanName":"s3ClientSecond"}',
            name: "1765264122801_21. DSST. Hốih Thông_convert_docx.pdf",
            size: "0.66",
            downloadding: false,
          },
        ],
        name: "QD-THADS.21/2025/QĐST-DS.Ông Hốih Thông",
        requester_1: "",
        sdtldtha: "986804734",
        filest_convert: null,
        xuphat: "",
        tamgiudambao: "",
        link: "https://kyta.fpt.com/thads-tracuuqd/?lookup=K7ea8Cnda7",
        hotenldtha: "Hoàng Minh Đông",
        emailvanthu: "vanthu.dng@moj.gov.vn",
        emailchv: "thuantn.qnm@moj.gov.vn",
        phongtoataikhoan: "",
        tieptuckebien: "",
        loaian: "Dân sự",
        filetlkhac_convert: null,
        hoantra: "",
        filest: null,
        hotentruongkvchanhvp: "Trần Ngọc Thuận",
        tinh: "Đà Nẵng",
        hotenvanthu: "Văn thư đơn vị TP Đà Nẵng",
        ndcc_convert:
          "Căn cứ Quyết định số 21/2025/QĐST-DS ngày 05 tháng 11 năm 2025 của Tòa án nhân dân Khu vực 12 - Đà Nẵng.",
        hoanlai: "",
        tieptuctamgiu: "",
        tichthusungcongsotien: "",
        anphicapduong: "",
        filecv_convert: "",
        filecv: "",
        dstoi: [
          ["Chương", "Mục", "Điều"],
          ["", "", ""],
          ["", "", ""],
        ],
        notificationSms: "",
        notificationsdd: "",
        qd1ghichu: "Ra quyết định",
        anphilaodongpt: "",
        filett: null,
        huyquyetdinh: "",
        boithuongnn: "",
        thuhoisotien: "",
        tichthutienhuy: "",
      },
      totalMoney: 300000,
      totalReceived: 0,
      remainingAmount: 300000,
    },
    enforcementDocumentRequests: [
      {
        enforcementDocument: {
          resourceType: "attatch",
          number: "5576/QĐ-THADS",
          name: "QĐ THADS 21/2025/QĐST-DS Ông Hốih Thông",
          releaseDate: "2025-12-11T02:03:53Z",
          submissionDate: "2025-12-09T07:58:38Z",
          page: null,
          businessType: "attach",
          documentType: "qdtha",
          status: "approved",
          resourceSystem: "eQD",
          butLuc: "1",
          deletionFlag: false,
        },
        objectStorages: [
          {
            resourceId: "judgment_decision_000061OWIqlnQsJpKEEgRx",
            fileName: "QĐ THADS 21/2025/QĐST-DS Ông Hốih Thông",
            typeLocation: null,
            code: null,
            beanName: "s3ClientSecond",
            bucketName: "prod-2025-envelope-second",
            keyName:
              "12/completed//storage-01/5682/000061RmIL0EC1gKm6DLmCGBPK.pdf",
            documentType: "envelope",
            resourceType: "DOCUMENT_TYPE_QDTHA",
            contentType: "application/pdf",
            documentSize: 1738720,
            resourceSystem: "envelope",
            description: null,
            envelopeId: "0000688kCVbEh1XLx0xqpSw0AV",
          },
        ],
      },
      {
        enforcementDocument: {
          resourceType: "attatch",
          number: "5576/QĐ-THADS",
          name: "21. DSST. Hốih Thông.pdf",
          releaseDate: "2025-12-11T02:03:53Z",
          submissionDate: "2025-12-09T07:58:38Z",
          page: null,
          businessType: "attach",
          documentType: "qdtha",
          status: "approved",
          resourceSystem: "eQD",
          butLuc: "2",
          deletionFlag: false,
        },
        objectStorages: [
          {
            resourceId: "judgment_decision_000061OWIqlnQsJpKEEgRx",
            fileName: "21. DSST. Hốih Thông.pdf",
            typeLocation: null,
            code: null,
            beanName: "s3ClientSecond",
            bucketName: "econ-eform-demo-hn2",
            keyName:
              "anonymous/20251209/1765264122801_21. DSST. Hốih Thông.pdf",
            documentType: "erequest",
            resourceType: "attatch",
            contentType: null,
            documentSize: 692060,
            resourceSystem: "eRequest",
            description: null,
            envelopeId: null,
          },
        ],
      },
      {
        enforcementDocument: {
          resourceType: "attatch",
          number: "5576/QĐ-THADS",
          name: "1765264122801_21. DSST. Hốih Thông_convert_docx.pdf",
          releaseDate: "2025-12-11T02:03:53Z",
          submissionDate: "2025-12-09T07:58:38Z",
          page: null,
          businessType: "attach",
          documentType: "qdtha",
          status: "approved",
          resourceSystem: "eQD",
          butLuc: "3",
          deletionFlag: false,
        },
        objectStorages: [
          {
            resourceId: "judgment_decision_000061OWIqlnQsJpKEEgRx",
            fileName: "1765264122801_21. DSST. Hốih Thông_convert_docx.pdf",
            typeLocation: null,
            code: null,
            beanName: "s3ClientSecond",
            bucketName: "econ-eform-demo-hn2",
            keyName:
              "anonymous/20251209/1765264122801_21. DSST. Hốih Thông_convert_docx.pdf",
            documentType: "erequest",
            resourceType: "attatch",
            contentType: null,
            documentSize: 692060,
            resourceSystem: "eRequest",
            description: null,
            envelopeId: null,
          },
        ],
      },
      {
        enforcementDocument: {
          resourceType: "attatch",
          number: "5576/QĐ-THADS",
          name: "File ký QDTHA chủ dộng_QT4_TH(Chánh VP_2).pdf",
          releaseDate: "2025-12-11T02:03:53Z",
          submissionDate: "2025-12-09T07:58:38Z",
          page: null,
          businessType: "attach",
          documentType: "qdtha",
          status: "approved",
          resourceSystem: "eQD",
          butLuc: "4",
          deletionFlag: false,
        },
        objectStorages: [
          {
            resourceId: "judgment_decision_000061OWIqlnQsJpKEEgRx",
            fileName: "File ký QDTHA chủ dộng_QT4_TH(Chánh VP_2).pdf",
            typeLocation: null,
            code: null,
            beanName: "s3ClientSecond",
            bucketName: "econ-eform-demo-hn2",
            keyName:
              "anonymous/20251211/1765418568902_File ký QDTHA chủ dộng_QT4_TH(Chánh VP_2).pdf",
            documentType: "erequest",
            resourceType: "attatch",
            contentType: null,
            documentSize: 1738714,
            resourceSystem: "eRequest",
            description: null,
            envelopeId: null,
          },
        ],
      },
    ],
    enforcementParties: [
      {
        name: "Hốih Thông",
        type: "P",
        attrs: {
          dob: null,
          ma_xa: null,
          ma_tinh: null,
          quoc_tich: null,
          represent: null,
          chuc_danh_dai_dien: null,
        },
        email: null,
        gender: null,
        birthDay: "1996",
        subjects: "nptha",
        description: null,
        phoneNumber: null,
        deletionFlag: false,
        identification: null,
        permanentAddress: "Thôn Aró, xã Tây Giang, thành phố Đà Nẵng",
        temporaryAddress: "Thôn Aró, xã Tây Giang, thành phố Đà Nẵng",
      },
      {
        name: "Thi hành án dân sự thành phố Đà Nẵng",
        type: "O",
        attrs: {
          dob: null,
          ma_xa: null,
          ma_tinh: null,
          quoc_tich: null,
          represent: null,
          chuc_danh_dai_dien: null,
        },
        email: null,
        gender: null,
        birthDay: null,
        subjects: "ndtha",
        description: null,
        phoneNumber: null,
        deletionFlag: false,
        identification: null,
        permanentAddress: null,
        temporaryAddress: null,
      },
    ],
    businessOperationDetails: [
      {
        note: null,
        paid: 0,
        rest: 300000,
        type: "tich_thu_tien",
        attrs: {
          currency: "VND",
        },
        issue: null,
        money: 300000,
        exempt: null,
        period: "thongbaoquyetdinhtha",
        reason: null,
        reduce: null,
        status: "dangthihanh",
        addition: null,
        assetType: null,
        description: "số tiền tạm ứng lệ phí",
        obligorName: {
          html: "Hốih Thông",
          base64: null,
        },
        postponedTo: null,
        businessType: "financial",
        personalInfos: null,
        postponedFrom: null,
        processingType: null,
        donvinhanutxlts: null,
        idhosonhanUTXLTS: null,
        relatedBusinessId: null,
        emailchvnhanUTXLTS: null,
        obligorName: {
          html: "Thi hành án dân sự thành phố Đà Nẵng",
          base64: null,
        },
      },
    ],
  },
];

// Danh sách email cần chạy
const emails = [

"test_anhvtv.hni@moj.gov.vn",

];

// Cấu hình API
const API_URL =
  "https://econtract.fpt.com/app/services/thads-tctha/api/enforcements/save-internal";

const getHeaders = () => ({
  accept: "application/json, text/plain, */*",
  "content-type": "application/json",
  Authorization: `Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aSI6eyJncm91cHNOYW1lIjpbIkFETUlOIl0sInJvbGVzIjpbMTg3OV0sImdyb3VwcyI6WzExNDc3XSwiaXBBY2Nlc3MiOltdLCJsb2dpbiI6ImN1c3RvbWVyc3Vwb3J0QGdtYWlsLmNvbSIsImZvbGRlcklkIjoiMDAwMDYxMUczc2tPTm1za09ObU1yYXFVZzhhQSIsImZvbGRlclBhdGgiOiIvc3RvcmFnZS0wMS81NjgyIiwiZGJTdWZmaXgiOiIwMDAwNiIsImxhbmdLZXkiOiJ2aSIsImN1c3RJZCI6NTY4Miwib3JnSW4iOiIvNTY4Mi8xMjE2MCIsImlkIjoxNjc2NjksImVtYWlsIjoiY3VzdG9tZXJzdXBvcnRAZ21haWwuY29tIn0sInVzZXJfbmFtZSI6ImN1c3RvbWVyc3Vwb3J0QGdtYWlsLmNvbSIsInNjb3BlIjpbIm9wZW5pZCJdLCJleHAiOjE3Njc2ODQxODIsImlhdCI6MTc2NzY4MjM4MiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9VU0VSX1JFU1RSSUNUIiwiUk9MRV9DVVNUX1JFUE9SVCIsIlJPTEVfVVNFUiIsIlJPTEVfQ1VTVF9ET0MiLCJST0xFX09SR19BRE1JTiIsIlJPTEVfQ1VTVF9TVEFGRiIsIlJPTEVfQ1VTVF9WSUVXRVIiXSwianRpIjoiYmMzMDYyMmItYzI4MC00ZWNiLWFmZDItN2U3NzBlZDUxMTc2IiwiY2xpZW50X2lkIjoid2ViX2FwcCJ9.HKBYoUBHiaPWXFtxwBwXpKHx6JVaFC4CURGYHxd5Vvj0swHoYE8A6kwSRD-EZjggxN-ObIX71pSuBkSrJ0jIggTFPF9CTAnpQByLiXV8MzIgItWG-bmEoddaEYbhY1oywpMB3iyGmuqZjarB3gDeslFt9UAUZE9QI1zFVHznjkr7vRo_Ysnn5Tbeo1k9224ts-NijvvnagZSN23tnlzcGYNF7PxvGTvAeOSXCQioOQQ1Yp8mmoQypKV5ofECO-IXzVr_eUQwYEjOtLJnYDhHHlBLyx5PfNsRuE8RdD1o-YOn031u2xmKnrAxLdVV8vXWnwkIWCEbiuo6NLhDtaLa4A`,
  "user-agent":
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36",
});

// Hàm gửi request
const sendRequest = async (payload, email, index) => {
  try {
    // Thay đổi trường assignee theo yêu cầu
    if (payload.enforcement) {
      payload.enforcement.assignee = email;
    } else {
      console.warn(`⚠️ Hồ sơ ${index + 1} thiếu trường enforcement!`);
      return;
    }
    // Gọi API
    const response = await axios.post(API_URL, payload, {
      headers: getHeaders(),
      httpsAgent: agent,
    });

    console.log(
      `✅ [${email}] Hồ sơ ${index + 1}: Thành công (Status: ${
        response.status
      })`
    );
  } catch (error) {
    console.log("error", error);
    const status = error.response ? error.response.status : "Unknown";
    const msg = error.response
      ? JSON.stringify(error.response.data)
      : error.message;
    console.error(
      `❌ [${email}] Hồ sơ ${index + 1}: Thất bại (Status: ${status}) - ${msg}`
    );
  }
};

// Hàm chạy chính
const runBatchJob = async () => {
  console.log(
    `Bắt đầu xử lý: ${emails.length} emails x ${hs.length} hồ sơ = ${
      emails.length * hs.length
    } requests\n`
  );

  for (const email of emails) {
    console.log(`--- Đang xử lý cho email: ${email} ---`);

    const promises = hs.map((record, index) =>
      sendRequest(record, email, index)
    );

    await Promise.all(promises);
  }

  console.log("\n🏁 Hoàn tất công việc!");
};

runBatchJob();